export type Answer = -1 | 0 | 1 | undefined;

export type CardinalId = 'besengu'
  | 'arborelius'
  | 'aveline'
  | 'bagnasco'
  | 'bo'
  | 'brislin'
  | 'burke'
  | 'eijk'
  | 'erdo'
  | 'filoni'
  | 'koch'
  | 'muller'
  | 'ouellet'
  | 'parolin'
  | 'piacenza'
  | 'pizzabella'
  | 'don'
  | 'sarah'
  | 'sturla'
  | 'tagle'
  | 'mendonca'
  | 'zuppi';